-- 011_storage_policies.sql
-- Bucket: `learning-materials` (private). Reads happen only via signed URLs
-- generated by the service-role client; writes happen only via the service-role
-- client. So we explicitly DENY all anon / authenticated direct access.

-- NOTE: create the bucket itself in the Supabase dashboard (Storage → New
-- bucket → name `learning-materials`, set "Public" off). Then run this file.

-- Drop any default permissive policies if they exist (Supabase sometimes
-- adds an "Allow all" policy on new private buckets).
do $$
begin
  if exists (select 1 from pg_policies where schemaname='storage' and tablename='objects' and policyname='Public Access') then
    execute 'drop policy "Public Access" on storage.objects';
  end if;
exception when others then
  null;
end$$;

-- Read access: only allow signed URLs. SvelteKit calls
-- `supabase.storage.from('learning-materials').createSignedUrl(path, ttl)`
-- on the server using the service-role client; the browser then fetches the
-- short-lived signed URL directly from Storage.
-- The policy below additionally allows authenticated users to list/get
-- objects in this bucket through the regular API _only for read_, so that
-- admin tooling works. Tighten further if you don't need this.
create policy lm_read_authenticated on storage.objects
  for select to authenticated
  using (bucket_id = 'learning-materials');

-- Writes (insert/update/delete) are restricted to admins, executed via the
-- service-role client which already bypasses RLS. Public/anon get nothing.
create policy lm_admin_write on storage.objects
  for all to authenticated
  using (bucket_id = 'learning-materials' and public.is_admin())
  with check (bucket_id = 'learning-materials' and public.is_admin());
